const languages = [
  "Mandarin Chinese",
  "Spanish",
  "English",
  "Hindi",
  "Bengali",
  "Portuguese",
  "Russian",
  "Japanese",
  "Western Punjabi",
  "Marathi",
  "Telugu",
  "Turkish",
  "Korean",
  "French",
  "German",
  "Vietnamese",
  "Tamil",
  "Yue Chinese",
  "Urdu",
  "Javanese",
  "Italian",
  "Egyptian Arabic",
  "Gujarati",
  "Iranian Persian",
  "Bhojpuri",
  "Min Nan Chinese",
  "Hakka Chinese",
  "Jin Chinese",
  "Hausa",
  "Kannada",
  "Indonesian",
  "Polish",
  "Yoruba",
  "Xiang Chinese",
  "Malayalam",
  "Odia",
  "Maithili",
  "Burmese",
  "Eastern Punjabi",
  "Sunda",
  "Sudanese Arabic",
  "Algerian Arabic",
  "Moroccan Arabic",
  "Ukrainian",
  "Igbo",
  "Northern Uzbek",
  "Sindhi",
  "North Levantine Arabic",
  "Romanian",
  "Tagalog",
  "Dutch",
  "Saʽidi Arabic",
  "Gan Chinese",
  "Amharic",
  "Northern Pashto",
  "Magahi",
  "Thai",
  "Saraiki",
  "Khmer",
  "Chhattisgarhi",
  "Somali",
  "Malaysian",
  "Cebuano",
  "Nepali",
  "Mesopotamian Arabic",
  "Assamese",
  "Sinhalese",
  "Northern Kurdish",
  "Hejazi Arabic",
  "Nigerian Fulfulde",
  "Bavarian",
  "South Azerbaijani",
  "Greek",
  "Chittagonian",
  "Kazakh",
  "Deccan",
  "Hungarian",
  "Kinyarwanda",
  "Zulu",
  "South Levantine Arabic",
  "Tunisian Arabic",
  "Sanaani Spoken Arabic",
  "Min Bei Chinese",
  "Southern Pashto",
  "Rundi",
  "Czech",
  "Taʽizzi-Adeni Arabic",
  "Uyghur",
  "Min Dong Chinese",
  "Sylheti",
  "Mandarin",
  "Quechua",
  "Kirundi",
  "Swedish",
  "Hmong",
  "Shona",
  "Uighur",
  "Hiligaynon",
  "Mossi",
  "Xhosa",
  "Belarusian",
  "Balochi",
  "Konkani",
];

export default languages;
